apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web-application-h2
  name: web-application-h2
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: web-application-h2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-application-h2
    spec:
      containers:
      - image: murilofelpeto/web-application-h2:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: web-application-h2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: web-application-h2
  name: web-application-h2
  namespace: default
spec:
  ports:
  - nodePort: 30702
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-application-h2
  sessionAffinity: ClientIP
  type: LoadBalancer