apiVersion: v1
kind: Service
metadata:
   labels:
      app: todo-web-application
   name: todo-web-application
spec:
   type: LoadBalance
   ports:
   -  name: '8080'
      port: 8080
      targetPort: 8080
   selector:
      app: todo-web-application