apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-database-data-volume
  name: mysql-database-data-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      database: mysql
   name: mysql
spec:
   replicas: 1
   selector:
      matchLabels:
         database: mysql
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            database: mysql
      spec:
         containers:
         -  env:
            -  name: MYSQL_DATABASE
               value: todos
            -  name: MYSQL_PASSWORD
               value: dummytodos
            -  name: MYSQL_ROOT_PASSWORD
               value: dummypassword
            -  name: MYSQL_USER
               value: todos-user
            image: mysql:5.7
            args:
               - "--ignore-db-dir=lost+found"
            imagePullPolicy: ''
            name: mysql
            ports:
            -  containerPort: 3306
            volumeMounts:
            -  mountPath: /var/lib/mysql
               name: mysql-database-data-volume
         restartPolicy: Always
         serviceAccountName: ''
         volumes:
         -  name: mysql-database-data-volume
            persistentVolumeClaim:
               claimName: mysql-database-data-volume
---
apiVersion: v1
kind: Service
metadata:
   labels:
      database: mysql
   name: mysql
spec:
   type: ClusterIP
   ports:
   -  name: '3306'
      port: 3306
      targetPort: 3306
   selector:
      database: mysql           