apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      app: todo-web-application
   name: todo-web-application
spec:
   replicas: 2
   selector:
      matchLabels:
         app: todo-web-application
   template:
      metadata:
         labels:
            app: todo-web-application
      spec:
         containers:
         -  env:
            -  name: RDS_DB_NAME
               valueFrom:
                  configMapKeyRef:
                     key: RDS_DB_NAME
                     name: todo-web-application-config # Nome do arquivo de config
            -  name: RDS_HOSTNAME
               valueFrom:
                  secretKeyRef:
                     key: RDS_HOSTNAME
                     name: todo-web-application-config
            -  name: RDS_PASSWORD
               valueFrom:
                  configMapKeyRef:
                     key: RDS_PASSWORD
                     name: todo-web-application-secrets
            -  name: RDS_PORT
               valueFrom:
                  configMapKeyRef:
                     key: RDS_PORT
                     name: todo-web-application-config
            -  name: RDS_USERNAME
               valueFrom:
                  configMapKeyRef:
                     key: RDS_USERNAME
                     name: todo-web-application-config
            image: murilofelpeto/web-application-mysql:0.0.2-RELEASE
            imagePullPolicy: ''
            name: todo-web-application
            ports:
            -  containerPort: 8080
         restartPolicy: Always
         serviceAccountName: ''
         volumes: null
---
apiVersion: v1
kind: Service
metadata:
   labels:
      app: todo-web-application
   name: todo-web-application
spec:
   type: LoadBalancer
   ports:
   -  name: '8080'
      port: 8080
      targetPort: 8080
   selector:
      app: todo-web-application