apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   labels:
      app: currency-conversion
   name: currency-conversion
   namespace: default
spec:
   replicas: 2 #CHANGE
   minReadySeconds: 45
   selector:
      matchLabels:
         app: currency-conversion
   strategy:
      rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
      type: RollingUpdate
   template:
      metadata:
         labels:
            app: currency-conversion
      spec:
         containers:
         -  image: murilofelpeto/currency-conversion-microservice:0.0.1-SNAPSHOT #CHANGE
            imagePullPolicy: IfNotPresent
            name: currency-conversion
            env:
            -  name: CURRENCY_EXCHANGE_URI
               value: http://currency-exchange
#          - name: SPRING_PROFILES_ACTIVE
#            value: kubernetes
         restartPolicy: Always
         terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
   labels: #PODS
      app: currency-conversion
   name: currency-conversion
   namespace: default
spec:
   ports:
   -  port: 8100
      protocol: TCP
      targetPort: 8100 #CHANGE # nodePort: 30701 #CHANGE
   selector: #CHANGE
      app: currency-conversion
   sessionAffinity: None #CHANGE
   type: LoadBalancer