apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web-application-h2
    environment: development
  name: web-application-h2-deploy
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: web-application-h2
      environment: development
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-application-h2
        environment: development
    spec:
      containers:
      - image: murilofelpeto/web-application-h2:0.0.1-RELEASE
        imagePullPolicy: IfNotPresent
        name: web-application-h2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-application-h2
    environment: development
  name: web-application-h2-service
  namespace: default
spec:
  ports:
  - nodePort: 30702
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-application-h2
    environment: development
  sessionAffinity: ClientIP # Preservar o cache. Um IP irá sempre bater no mesmo pod.
  type: LoadBalancer